name: Test, Build & Deploy

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  clojure:
    name: Test & Build Clojure
    env:
      DOCKER: "29.0.0"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: install clojure tools
        uses: DeLaGuardo/setup-clojure@9.5
        with:
          lein: latest
      - run: ./init-db.sh
        name: start DB
        working-directory: dev/script
      - run: ./init-influx.sh
        name: start Influx
        working-directory: dev/script
      - run: ./init-agent.sh
        name: start Agent
        working-directory: dev/script
      - run: ./start-dind.sh
        name: start Docker in Docker
        working-directory: dev/script
      - run: lein deps
      - run: lein test :all
      - run: lein uberjar
      - name: upload release jar
        uses: actions/upload-artifact@v4
        with:
          name: swarmpit.jar
          path: target/swarmpit.jar
  docker:
    name: Build and push docker
    runs-on: ubuntu-latest
    needs: clojure
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        name: download release jar
        with:
          name: swarmpit.jar
          path: target
      - name: set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: login to GHCR
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/master' }}
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/swarmpit:latest
            ghcr.io/${{ github.repository_owner }}/swarmpit:${{ github.sha }}
